name: 'beneissue'
description: 'AI-powered GitHub issue automation'
author: 'opendataloader-project'

branding:
  icon: 'zap'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: false
  langchain-api-key:
    description: 'LangChain API key for LangSmith tracing'
    required: false
  langchain-project:
    description: 'LangSmith project name for tracing'
    required: false
    default: 'beneissue'
  supabase-url:
    description: 'Supabase project URL for metrics storage'
    required: false
  supabase-service-key:
    description: 'Supabase service role key for metrics storage'
    required: false
  command:
    description: 'Command to run (triage, analyze, fix, check)'
    required: false
    default: 'analyze'
  issue-number:
    description: 'Issue number to process (defaults to event issue)'
    required: false
  verbose:
    description: 'Enable verbose output for debugging'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install beneissue
      shell: bash
      run: uv pip install --system beneissue

    - name: Run beneissue
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        LANGCHAIN_API_KEY: ${{ inputs.langchain-api-key }}
        LANGCHAIN_TRACING_V2: ${{ inputs.langchain-api-key && 'true' || 'false' }}
        LANGCHAIN_PROJECT: ${{ inputs.langchain-project }}
        SUPABASE_URL: ${{ inputs.supabase-url }}
        SUPABASE_SERVICE_KEY: ${{ inputs.supabase-service-key }}
      run: |
        COMMAND="${{ inputs.command }}"

        # check command doesn't need issue number
        if [ "$COMMAND" = "check" ]; then
          beneissue check "${{ github.repository }}"
          exit 0
        fi

        ISSUE_NUMBER="${{ inputs.issue-number }}"
        if [ -z "$ISSUE_NUMBER" ]; then
          ISSUE_NUMBER="${{ github.event.issue.number }}"
        fi

        if [ -z "$ISSUE_NUMBER" ]; then
          echo "Error: No issue number provided"
          exit 1
        fi

        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" = "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi

        DRY_RUN_FLAG=""
        if [ "$BENEISSUE_DRY_RUN" = "true" ]; then
          DRY_RUN_FLAG="--dry-run"
        fi

        NO_ACTION_FLAG=""
        if [ "$BENEISSUE_NO_ACTION" = "true" ]; then
          NO_ACTION_FLAG="--no-action"
        fi

        beneissue "$COMMAND" "${{ github.repository }}" --issue "$ISSUE_NUMBER" $VERBOSE_FLAG $DRY_RUN_FLAG $NO_ACTION_FLAG
